sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck:stable

script:
  - docker run koalaman/shellcheck:stable --version
  - docker run -v $(pwd):/scripts koalaman/shellcheck:stable --color=always --check-sourced --external-sources /scripts/usr/local/modpd/bin/modpd
  - docker run -v $(pwd):/scripts koalaman/shellcheck:stable --color=always --check-sourced --external-sources /scripts/etc/init.d/modpd

matrix:
  fast_finish: true

notifications:
  email: false
