#!/usr/bin/env bash

# shellcheck disable=SC2034

#-----------------------------------------------------------------------
#
# DONT DELETE THIS FILE, because its the database for check_modpd !!!
#
# Automatically generated by:	modpd
# Generated at:			2017-09-30 19:10:31
# Author:			Christian Zettel (ccztux)
# Last modification:		2017-09-28
# Version:			1.0.3-alpha1
#
#-----------------------------------------------------------------------



# shows how long modpd is running in seconds
modpd_runtime="1"

# shows how much nrdp or nsca jobs where handled in one statistic data period (300 seconds)
script_job_counter_total="0"

# shows how much nrdp or nsca jobs where handled successfully in one statistic data period (300 seconds)
script_job_counter_ok="0"

# shows how much nrdp or nsca jobs where handled unsuccessfully in one statistic data period (300 seconds)
script_job_counter_nok="0"

# shows how much nrdp or nsca jobs timed out in one statistic data period (300 seconds)
script_job_counter_timeout="0"

# shows how much host checks where handled in one statistic data period (300 seconds)
script_host_counter="0"

# shows how much service checks where handled in one statistic data period (300 seconds)
script_service_counter="0"

# shows how much invalid datasets where received in one statistic data period (300 seconds)
script_invalid_data_counter="0"
