#!/usr/bin/env bash

#-----------------------------------------------------------------------
#
# Automatically generated by:	modpd
# Generated at:			2017-09-28 19:35:33
# Author:			Christian Zettel (ccztux)
# Last modification:		2017-09-28
# Version:			1.0.3-alpha1
#
#-----------------------------------------------------------------------



# shows how long modpd is running in seconds
modpd_runtime="0"

# shows how much nrdp or nsca jobs where handled since program start
script_job_counter_total="0"

# shows how much nrdp or nsca jobs where handled successfully since program start
script_job_counter_ok="0"

# shows how much nrdp or nsca jobs where handled unsuccessfully since program start
script_job_counter_nok="0"

# shows how much nrdp or nsca jobs timed out since program start
script_job_counter_timeout="0"

# shows how much host checks where handled since program start
script_host_counter="0"

# shows how much service checks where handled since program start
script_service_counter="0"

# shows how much invalid datasets where received since program start
script_invalid_data_counter="0"
