name: ShellCheck (devel)
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

permissions:
  contents: read

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
      - name: Get the stable ShellCheck container
        run: |
          sudo docker pull koalaman/shellcheck:stable

      - name: Show ShellCheck version
        run: |
          docker run koalaman/shellcheck:stable --version

      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ShellCheck our scripts
        run: |
          docker run -v $(pwd):/scripts koalaman/shellcheck:stable --color=always --check-sourced --external-sources /scripts/usr/bin/modpd
          docker run -v $(pwd):/scripts koalaman/shellcheck:stable --color=always --check-sourced --external-sources /scripts/usr/libexec/modpd/send_icinga2_api.sh
